name: sample_pr_merged
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - uses: ryubb/change-notion-page-status@v0.0.2
      with:
        notion-key: ${{ secrets.NOTION_KEY }}
        status-property: "Status"
        status-value: "Completed"
